### ISSUE TITLE
Disabling display of the `borg-build-mode` buffer

### ISSUE THREAD

**Issue by grtcdr** [emacscollective/borg#145]
Hi Jonas,

Many of us use `display-buffer-alist` to modify the placement of our windows. I expected I'd be able to hide `*Borg Build*` buffers [^1], but that doesn't work with either of the following configurations:

```emacs-lisp
;; Using a regular expression:
(setq display-buffer-alist
   '(("\\*Borg Build\\*"
      (display-buffer-no-window)))

;; Using cons cells:
(setq display-buffer-alist
   '((major-mode . borg-build-mode)
     (display-buffer-no-window)))
```

I expect this is happening because `borg--build-interactive` isn't directly using `display-buffer` but other buffer display functions that hardcode its window placement. Would you be open to relying on `display-buffer` instead?

Thank you for your time and work,

[^1]: It's unlikely that I'd shutdown Emacs while the process is still running, and even then, Emacs will warn me in the presence of a running process or an unsaved buffer because I've configured the user service to shutdown via `(save-buffers-kill-emacs)`.

**Comment by tarsius** [comment]
`borg--build-interactive` calls `pop-to-buffer-same-window, which just calls `pop-to-buffer` while specifying an ACTION. That calls `display-buffer` and if, and only if, that returns a window, it additionally selects that.

The docstring of `display-buffer` contains (emphasis mine):

> `display-buffer` builds a list of action functions and an action
> alist by combining any action functions and alists specified by
> `display-buffer-overriding-action`, **`display-buffer-alist`, the**
> **ACTION argument**, `display-buffer-base-action`, and
> `display-buffer-fallback-action` **(in order)**.

So `display-buffer-alist` overrides the ACTION argument, rendering your request moot. Your goal can be accomplished without requiring any changes to Borg.

Your second approach won't work in this case because the mode is set after displaying the buffer. (That may be something I should change.)

The problem with your first approach is that specifying the "do nothing" action is not enough. Additionally you have to specify that is okay for an action to do nothing: :stuck_out_tongue_winking_eye:, i.e.:

```elisp
(setq display-buffer-alist
      '(("\\`\\*Borg Build\\*\\'"
         display-buffer-no-window
         (allow-no-window . t))))
```

**Comment by tarsius** [comment]
The major-mode is now set before the buffer is displayed.

**Comment by tarsius** [comment]
You're welcome!
