### ISSUE TITLE
Discussions redirect points to organization

### ISSUE THREAD

**Issue by darkfeline** [emacscollective/borg#150]
The Discussions redirect page https://github.com/emacscollective/.github/wiki/Discussions-redirect (which is linked when trying to create a new Issue) is on the organization page, not the borg repo.

So following the instructions on the Discussions redirect page leads to the organization Discussions (https://github.com/orgs/emacscollective/discussions), not the borg repo Discussions (https://github.com/emacscollective/borg/discussions).

This seems unintended AFAICT.

Edit: I didn't see the "after returning to the previous page" on that page.  Maybe it should be emphasized, or the page should include direct links to the repo Discussion pages.

**Comment by darkfeline** [comment]
Semi-related: is it possible to transfer https://github.com/orgs/emacscollective/discussions/1 to `emacscollective/borg`?  I'm not familiar with GitHub Discussions, but at least it seems that I cannot do it.

**Comment by tarsius** [comment]
I was able to transfer. I think transferring "topics" is only available to admins of an organization.

I'll look into approving the page in the new year.

**Comment by tarsius** [comment]
> The Discussions redirect page https://github.com/emacscollective/.github/wiki/Discussions-redirect (which is linked when trying to create a new Issue) is on the organization page, not the borg repo.

I am aware of this.

I do not want to maintain nearly identical copies of https://github.com/emacscollective/.github/tree/c/.github/ISSUE_TEMPLATE in every repository. Because these templates don't have any, uhm, templating support, I cannot link to any repository specific pages. I.e., I cannot do this:

```diff
 blank_issues_enabled: false
 contact_links:
   - name: "For SUPPORT ☛ use the Discussions feature of this repository"
-    url: https://github.com/emacscollective/.github/wiki/Discussions-redirect
+    url: https://github.com/{{ repository-owner-and-name }}/discussions
     about: Please search, ask and answer questions here.
```

That is why I added this indirection and why the wiki page contains the following (in particular the emphasized part):

> This is where you can find the link to the discussion page ***(after returning to the previous page)***:

I've decided to stick with this indirection kludge, but replace the instructions in the Discussions-redirect page, with a list of hard-coded links.
