### ISSUE TITLE
`make build` doesn't respect submodule variable?

### ISSUE THREAD

**Issue by dakra** [emacscollective/borg#37]
`slime` already has it's own autoload file and also own Makefile.
When "doing nothing", borg overwrites the `slime-autoloads.el` file
and leaves the submodule dirty.
So I set the variable `submodule.slime.build-step` to `make` like
in the documentation expecting that `borg-update-autoloads` is *not* called.

Now if I go to `lib/slime` and manually type `make`
or if I type in my config dir `make lib/slime` it works
and the submodule is not diry.
But calling `make build` changes/deletes the autoload file.
 
(Same issue with `realgud`)

**Comment by tarsius** [comment]
> But calling `make build` changes/deletes the autoload file.

I assume you are running that in `~/.emacs.d/`, not `~/.emacs.d/lib/slime`.

That runs the same target as just `make` without any any arguments, so I don't see how that could lead to different results.

> So I set the variable `submodule.slime.build-step` to `make` like in the documentation expecting that `borg-update-autoloads` is *not* called.

Looking at `borg-build` I don't see how that function could get called when `submodule.slime.build-step`'s *only* value is `make`.

**Comment by dakra** [comment]
Sorry, I wrote it confusing. I mean that I call `make` in `~/.emacs.d/lib/slime`.

So I just tested it with a fresh `emacs.g` repo.
So to reproduce take a clean `emacs.g` repo and
assimilate first `hyperspec` (dependency) and then `slime`.

Then you'll see `slime-autoloads.el` changed.
Then undo the change and add `build-step = make` to the slime submodule.
Then `make lib/slime` "works" and nothing changes but
calling `make build` will delete the `slime-autoloads.el` file.

**Comment by tarsius** [comment]
> Then `make lib/slime` "works" and nothing changes but
calling `make build` will delete the `slime-autoloads.el` file.

Both of these commands, `cd ~/.emacs.d && make lib/slime` and `cd ~/.emacs.d && make` do the same thing for me (with regards to `slime`, the latter of course also builds all the other packages). Essentially they do `cd ~/.emacs.d/lib/slime && make`.

Borg only does `cd ~/.emacs.d/lib/slime && make`, i.e it uses Slime's own `Makefile` and that in turn causes `slime-autoloads.el` to become dirty. That's a defect of Slime and as the as the tracked `slime-autoloads.el` acknowledges:

> ;; JT@14/01/09: FIXME: This file should be auto-generated with autoload cookies.

Since there are only a handful of autoloaded commands, doing this should be trivial. Maybe you could contribute that to Slime?

**Comment by dakra** [comment]
> Both of these commands, cd ~/.emacs.d && make lib/slime and cd ~/.emacs.d && make do the same thing for me (with regards to slime, the latter of course also builds all the other packages). Essentially they do cd ~/.emacs.d/lib/slime && make

Hmm, for me ` ~/.emacs.d/lib/slime && make` doesn't leave the autoloads file dirty. Seems to be not touching it.
Have you set the slime submodule variable `build-step = make`?
If you do that than `cd ~/.emacs.d && make lib/slime` and `cd ~/.emacs.d && make` will do different things related to slime. The latter is deleting the autoload file while the first one just calls make from the slime directory.

> Since there are only a handful of autoloaded commands, doing this should be trivial. Maybe you could contribute that to Slime?

Good point. Regardless of this issue the autoload file should be auto-generated.
I'll put that on my todo list :)

**Comment by tarsius** [comment]
> Have you set the slime submodule variable build-step = make?

Sound of slapping hand on forehead...

**Comment by tarsius** [comment]
You are right, `make build`/`borg-batch-rebuild` *does* delete the autoload files - unlike `make lib/DRONE`/`borg-build`.

But I think it should keep doing that and that we shouldn't add a kludge for packages that track the autoload file. That is just wrong, and should be fixed instead of being worked around.

**Comment by dakra** [comment]
Sure. I have *a lot* of packages installed and only `slime` and `realgud` have a autoload file committed. I'll fix slime upstream. But `realgud` has a `realgud-recursive-autoloads.el` and this gets deleted as well. I didn't try to set it up under borg yet as I don't use it often but maybe borg should only delete CLONE-autoloads.el as this is also the only file `borg-update-autoloads` creates.

**Comment by tarsius** [comment]
> maybe borg should only delete CLONE-autoloads.el as this is also the only file `borg-update-autoloads` creates.

Makes sense, but that would complicate the `clean` target, which currently is just

```make
clean:
	@find lib -name '*-autoloads.el' -exec rm '{}' ';'
	@find lib -name '*.elc' -exec rm '{}' ';'
	@rm -f init.elc
```

The first command would have to be replaced with something involving `emacs -Q --batch ...borg...`.

I am not sure there actually is a legitimate reason to ever track a autoloads file. The name  `realgud-recursive-autoloads.el` suggests that the use of subdirectories poses some issues and that that is why `realgud` does track the file.

And indeed reading the related conversations in https://github.com/realgud/realgud/issues/84 and https://github.com/realgud/realgud/pull/94 confirm this. Here is the summary from the latter:

> RealGUD's file are neatly organized in subdirectories, but currently Emacs' autoloads generation doesn't recurse into subdirectories, and package.el doesn't do it either. Thus this PR adds a special autoload to realgud.el, which in turn loads a single file, realgud-recursive-autoloads.el, which contains statically built autoloads for RealGUD's subdirectories.

@cpitclaudel then goes on describing an alternative approach.

> We could have made this system even smarter and generated this autoloads file in an eval-when-compile form, but I'm not a big fan of running (somewhat) complex code while packages are installed.

That's probably what I will do in Magit once I start using subdirectories there. I am also not happy about it but I prefer this kludge over the approach taken by Realgud because to me tracking the generate autoloads is even more unfortunate.

But since Realgud chooses the other approach, we have to deal with it here. Fortunately the above also hints at what we have to do here. Please try whether this, or some variation, does the trick:

```
[submodule "realgud"]
	...
	build-step = make
```

The Realgud build tools seem to be implemented in Ruby and the `Makefile`s appear to only be a wrapper around that, so I am not sure if we have to run additional targets.

**Comment by dakra** [comment]
Thanks for the thorough answer.
I tried the `realgud` configure system but wasn't too successful.
First there was a bug (extra `)`) in the generated `configure` file and
now make fails in `js.el` that it can't find `load-relative` even though
the make steps before could find it.

Anyway, I saw that calling `make` is not the best idea anyway as it opens
a new instance for all the 100+ debuggers it has so it takes very long.

So I thought I just maybe I just do the autoloads file by calling
`(realgud--rebuild-recursive-autoloads)` which works but order is a bit
different so would leave the autoload file dirty.

Now I have a quick-hack solution and don't byte-compile realgud files
and just restore the previously deleted file:

``` ini
[submodule "realgud"]
        path = lib/realgud
        url = git@github.com:rocky/emacs-dbgr.git
        build-step = git checkout realgud-recursive-autoloads.el
````

Like I said before, I don't really use realgud so I don't care too much and don't want to spend hours trying to make a complicated upstream fix, when judging by your linked PR quite a bit of thought went into this build system/autoload config.

**Comment by tarsius** [comment]
> So I thought I just maybe I just do the autoloads file by calling `(realgud--rebuild-recursive-autoloads)` which works

Sounds like a good approach.

> but order is a bit different so would leave the autoload file dirty.

That's unfortunate but I suspect that that the maintainers would now get the same order as you, so this probably could be fixed.

> Now I have a quick-hack solution and don't byte-compile realgud files and just restore the previously deleted file:

This might work too:

``` ini
        build-step = borg-byte-compile
        build-step = borg-makeinfo
        build-step = git checkout realgud-recursive-autoloads.el
````

> Like I said before, I don't really use realgud so I don't care too much and don't want to spend hours trying to make a complicated upstream fix, when judging by your linked PR quite a bit of thought went into this build system/autoload config.

No problem. I am going to treat it as an upstream issue and I also don't want to invest time fixing. But I am hereby letting the maintainer @rocky and author of the autoload stuff @cpitclaudel know about it.
