### ISSUE TITLE
org string hardcoded in borg-batch-rebuild

### ISSUE THREAD

**Issue by dakra** [emacscollective/borg#39]
I didn't start with any of the `emacs.g` "templates" but build my own (as org config).
I assimilated the newest org-mode which is `https://code.orgmode.org/bzg/org-mode.git` so it makes sense that the drone is also called `org-mode` but looking at `borg-batch-rebuild` (and `emacs.g` `org` branch) I see that you name it only `org`.

I think it should detect and work with both names.

**Comment by tarsius** [comment]
> I think it should detect and work with both names.

In general the name of a drone doesn't matter, expect that `borg-{clone,assimilate}` won't know the url of the upstream repository so you have to type or yank it. But `borg-batch-rebuild` does indeed contain a special case for Org.

> I think it should detect and work with both names.

I think there are too reasons for why the name "org-mode" is sometimes used instead of just "org". 

1. That's what it was called historically. But since then the convention has evolved that a package should not be called "*-mode", the only exception possibly being packages that essentially provide nothing but the respective major-mode.

   The "main" or only library should also not be called "*-mode" and Org doesn't do that - there is a `org.el`, but no `org-mode`.el`. In my opinion the name of a package should match the name of the main library. There are very few exceptions: https://www.emacsmirror.net/stats/kludges.html#org195e8f6.

2. "Org" is a rather generic term/abbreviation, so taking about "org-mode" helps making it clear what the subject is. However in the context of Emacs packages "org" is not ambiguous.

Supporting both names in `borg-batch-rebuild` would mean adding a second order kludge, which goes against my desire to keep things simple and to favor conventions over customizability. So I would like to encourage you to use the name "org" instead. While "org-mode" makes sense too, I don't think it makes *more* sense than "org". By the way, in the [Org Elpa archive](https://orgmode.org/elpa.html), the package is called just "org" too.

**Comment by dakra** [comment]
Ok. Thanks for the explanation.
Since it's already documented in the manual I'll just close this issue and rename my drone to `org`.

**Comment by tarsius** [comment]
You are welcome and thanks for understanding.
