### ISSUE TITLE
borg-build asks for cloning epkgs

### ISSUE THREAD

**Issue by DamienCassou** [emacscollective/borg#63]
When running `M-x borg-build RET ace-link RET`, I get a `*Borg Build*` buffer with

```
(09:29:52) Building ace-link

Initializing drones...done (185 drones in 0.162s)
Clone https://github.com/emacsmirror/epkgs.git to /home/cassou/.emacs.d/epkgs/? (yes or no)
```

I don't want to clone epkgs in `~/.emacs.d/epkgs` because it is already in `~/.emacs.d/var/epkgs`.

**Comment by tarsius** [comment]
This has happened to me a few times too and I am not quite sure what's going on (though in my case it's in yet another place). I investigated a bit and the problem was that the value of the variable was wrong, but I could not figure out why that was so. I did suspect that it was due to some change/bug in `use-package`, but I could be completely wrong.

**Comment by tarsius** [comment]
Has this ever happened again? Not to me.

**Comment by DamienCassou** [comment]
Not once :-). I'm closing the issue.
