### ISSUE TITLE
Notification when repos move?

### ISSUE THREAD

**Issue by jabranham** [emacscollective/borg#73]
It would be nice if borg and epkg somehow integrated so that we could get notifications (or something) when repos move (e.g. org somewhat recently moved; several others have moved away from github).

**Comment by tarsius** [comment]
Here's something to get you started:

```lisp
(dolist (clone (borg-clones))
  (let* ((default-directory (borg-worktree clone))
         (a (magit-git-string "remote" "get-url" "origin"))
         (b (car (borg-get clone "url")))) ; FIXME
    (unless (magit--github-url-equal a b)  ; FIXME
      (message "%s => %s" a b))))
```

**Comment by jabranham** [comment]
Thanks. changing `a` or `b` to something like `(oref (epkg clone) repopage)` checks for upstream movements too.

**Comment by tarsius** [comment]
Yes, that makes more sense (except the correct slot is `url`).

```lisp
(defun borg-sync-drone-urls ()
  "Offer to update outdated upstream urls of all drones."
  (interactive)
  (let (moved)
    (dolist (drone (borg-clones))
      (let ((a (borg-get drone "url"))
            (b (ignore-errors (oref (epkg drone) url))))
        (when (and b (not (magit--forge-url-equal a b)))
          (push (list drone a b) moved))))
    (when (and moved
               (yes-or-no-p
                (concat (mapconcat (pcase-lambda (`(,drone ,a ,b))
                                     (format "%s: %s => %s" drone a b))
                                   moved "\n")
                        "\n\nThese upstream repositories appear to have moved."
                        "\s\sUpdate local configuration accordingly? ")))
      (let ((default-directory borg-user-emacs-directory))
        (pcase-dolist (`(,drone ,_ ,b) moved)
          (process-file "git" nil nil nil "config" "-f" ".gitmodules"
                        (format "submodule.%s.url" drone) b))
        (process-file "git" nil nil nil "submodule" "sync")))))
```

I hesitate to add something like this to `borg` itself because I generally don't want to add any features beyond the essentials. Also, this is still not good enough, for example when I ran it I got asked:

```
rainbow-mode: git@github.com:emacsmirror/rainbow-mode.git => https://git.savannah.gnu.org/git/emacs/elpa.git
elx: git@github.com:tarsius/elx.git => git@github.com:emacscollective/elx.git

These upstream repositories appear to have moved.  Update local configuration accordingly? (y or n) n
```

And learned that had forgotten to update the `elx` url, that's good. However I want to treat the Emacsmirror's `rainbow-mode` repository as the upstream (or at least at one point I did, will have to double-check, so I cannot just say "yes" here. Once the user has to be given the opportunity to choose which urls to update, things get more complicated.

So I am adding a wiki page for this instead.

**Comment by tarsius** [comment]
https://github.com/emacscollective/borg/wiki/Utilities

**Comment by dakra** [comment]
Where can I get `magit--forge-url-equal` from?
Doesn't seem to be in the magit repo
https://github.com/magit/magit/search?q=magit--forge-url-equal&unscoped_q=magit--forge-url-equal

**Comment by tarsius** [comment]
Use the (incorrectly named) `magit--github-url-equal` for now.

**Comment by jabranham** [comment]
Thanks!

**Comment by Thaodan** [comment]
Here's an updated version of the function adjusted for recent forge:
https://github.com/thaodan/emacs.d?tab=readme-ov-file#borg

The function also takes into account if the user uses SSH but Epkg returns https URL.
It also pays attention to if the drone is in Emacattack and the user uses that instead of the inactive upstream.
