### ISSUE TITLE
Question about emacsmirror and elpa

### ISSUE THREAD

**Issue by bwolf** [emacscollective/borg#85]
Sorry, I've found no better place where to put this: I'm using borg and a package for Emacs called eglot. The package eglot uses flymake and recently the developer of eglot decided to depend on `(flymake "1.0.2")` which is only available on [elpa](https://elpa.gnu.org/packages/flymake.html). I've read the introduction of emacsmirror, and got it that it only mirrors Melpa (btw.  which makes sense to me). To me it is unclear how to handle the situation.

It is the first time that I found a package which I heavily depend on, that changed somehow in an incompatible fashion. It was easy to work around (thanks to borg/git submodules) by checking out a working commit. Thus thank you for this wonderful piece of software.

One way to work around this, is to add the upstream git repo of flymake as a submodule. But is this the right thing to do? Btw. is the maintainers action (eglot) to add the dependency to an elpa package a temporary (and usual) way, until Emacs core (maybe) merges the updates into an Emacs release?

Again, sorry to bother you with this.

**Comment by tarsius** [comment]
> I've read the introduction of emacsmirror, and got it that it only mirrors Melpa

Actually the Emacsmirror contains a few hundred more packages than Melpa and the Epkgs database 42% more than Melpa. See https://www.emacsmirror.net/stats/compare.html. I am just no longer actively *searching* for new packages. Instead I semi-automatically add those that were recently added Melpa plus a few I happen to run into and find interesting. But yeah, https://www.emacsmirror.net doesn't say that explicitly.

> The package eglot uses flymake and recently the developer of eglot decided to depend on (flymake "1.0.2") which is only available on elpa.

So the problem is that the version built into Emacs 26.1 is 0.3 but `eglot` depends on 1.0.2, which so far has not made it into an Emacs release and has to be installed separately for now, right.

The Epkg database only supports "one version" of any given package. And with one exception it always prefers the built-in version (from the latest Emacs release) over a version from GNU Elpa or a third-party repository. The exception is `org`, which I feel is significant enough to deserve an exception.

Not so sure about `flymake`. However going forward this is probably going to happen more often and I will have to think about what I want to do in such cases and where to draw the line.

... researching ...

`flymake` is probably not going to make it. If it were imported into Elpa from a third-party Git repository, then I might add it. However it is being imported from the `master` branch of Emacs itself. That I cannot pull using Git alone.

> It was easy to work around (thanks to borg/git submodules) by checking out a working commit.

Wait what? Is it available from a separate repository after all?

**Comment by tarsius** [comment]
Looking at https://www.emacsmirror.net/stats/compare.html again I see that there actually is a second exception already. `ada-mode`. Also I could just get `flymake` from the Elpa repository. Extracting the history of a single package from the shared history in that repository is supported by my import tools. Finally it seems there are currently seven packages for which I might want to do that.

            | Epkg | Mirror | Attic | Emacs | Gelpa | Melpa
    builtin | 455  |        |       | 457   | 7     |

**Comment by bwolf** [comment]
> So the problem is that the version built into Emacs 26.1 is 0.3 but `eglot` depends on 1.0.2, which so far has not made it into an Emacs release and has to be installed separately for now, right.

Yes

> > It was easy to work around (thanks to borg/git submodules) by checking out a working commit.
> 
> Wait what? Is it available from a separate repository after all?

No, I was wrong about this one.

**Comment by tarsius** [comment]
"core" packages (i.e. those that are part of emacs itself, but also distributed on gnu elpa) are now being mirrored from emacs' master branch. Due to technical issues old history had to be discarded for the time being, but new commits should be pulled fairly regularly (about twice per month).

Eventually the full history will be imported, but currently this cannot be done because `git filter-repo` takes an hour per package, even if there is not change, and it grows the size of the package repo to 16GB.
