### ISSUE TITLE
Borg has very strong assumptions about directory structure.

### ISSUE THREAD

**Issue by thblt** [emacscollective/borg#9]
In various places, Borg seems to assume that:

 - the `.emacs.d` directory is the root of a git repository.
 - Drones are located in a `lib` directory at the root of a git repository.  

For example, the `borg-drones` function identify submodules which are actually drones by the fact that [their path start with `/lib`](https://github.com/emacscollective/borg/blob/master/borg.el#L183).  This is the case if and only if the two above assumptions are true.

Requiring a very specific layout may be a feature rather than a bug, but if this is the case, this feature is inconsistent with the fact that `borg-drone-directory` [tries to be smart](https://github.com/emacscollective/borg/blob/master/borg.el#L49-L54) when determining its actual location instead of failing when it isn't in `$GIT_ROOT/lib`

**Comment by tarsius** [comment]
> Requiring a very specific layout may be a feature rather than a bug, 

I indeed consider that a feature. Enforcing these directories makes it more likely that users can merge "feature branches" from one another, which could lead to a "distributed starter-kit" eventually. I am also the author of [`no-littering`](https://github.com/tarsius/no-littering) which adds `.emacs.d/{etc,var}` in addition to the `.emacs.d/{lib,bin}` introduced here.

> but if this is the case, this feature is inconsistent with the fact that `borg-drone-directory` [tries to be smart](https://github.com/emacscollective/borg/blob/master/borg.el#L49-L54) when determining its actual location instead of failing when it isn't in `$GIT_ROOT/lib` 

That's *another* feature. It allows cloning `emacs.g` to e.g. `/tmp/emacs.g` so that users can try out `borg` without having to first move their existing `~/.emacs.d` aside. This is part of what makes `emacs
-Q --load /tmp/emacs.g/init.el` possible.

**Comment by thblt** [comment]
Thanks for the clarification! 

The rationale for enforcing directory names seems sound, but I think actively enforcing them early would be of some help.  I was adding Borg to an existing configuration, and I spent some time trying to understand why it didn't see the drones it had assimilated.  The issue was that drones path was `~/.dotfiles/.emacs.d/drones`, and yet everything seemed to work well until it got asked to list its drones.  Maybe the `(defconst borg-drone-directory` could do some sanity check to be sure to fail early, or at least warn, early?

**Comment by tarsius** [comment]
I'll see what I can do, but I expect that will come in the form of documentation, not assertions.
