### ISSUE TITLE
The package database is now tracked as a text dump

### ISSUE THREAD

**Issue by tarsius** [emacscollective/borg#91]
The database is now being stored as a text file instead of in its binary form.  That gives us more useful diffs and most importantly it allows us to shrink the size of the repository.  To accomplish that the old history had to be removed and is now available at https://github.com/emacsmirror/epkgs-v4.  The database schemata revision is now 5.

All users will have to move aside the old repository (or delete it) and then clone the new repository:

```
cd ~/.emacs.d/
mv epkgs epkgs-v4
git clone git@github.com:emacsmirror/epkgs.git epkgs
```

**Comment by raxod502** [comment]
Oh, nice! So I think that it will still be helpful for me to maintain [emacsmirror-mirror](https://github.com/emacs-straight/emacsmirror-mirror) since a shallow clone of epkgs is 23MB whereas a shallow clone of emacsmirror-mirror is only 228KB, but the user experience will be improved for people who elect to use epkgs directly by means of

```elisp
(setq straight-recipes-emacsmirror-use-mirror nil)
```

If I understand correctly, this only modifies the SQL database format, and doesn't touch the rest of the repository, so `straight.el` should still be able to extract recipes from epkgs in the same way (i.e., no update required), namely by looking at the `attic` and `mirror` subdirectories and asking Git to inspect `.gitmodules`.

**Comment by tarsius** [comment]
That should work as before yes. One small difference is that Melpa, GNU Elpa and the Emacswiki are now being tracked as submodules but as long as you don't initialize those that shouldn't make a difference.

**Comment by fbergroth** [comment]
Perhaps obvious, but if you use no-littering you should clone into `var/epkgs` (or let `epkg-db` do it for you).
