### ISSUE TITLE
The default major mode when borg-assimilate failed

### ISSUE THREAD

**Issue by dalu98** [emacscollective/borg#96]
I want to know why `*Borg Git ...` is in `fundamental-mode` by default, it differs from `*Borg Build*`'s `borg-build-mode`. When I run into some network problem by running `borg-assimilate`, emacs will switch to `*Borg Git ...`, and I prefer to press `q` to quit this buffer.

Is this a feature? Thanks

---

Sorry to raised this question in an unrelated issue, because I thought it's just a minor question and not deserved to open a new issue for this😢

**Comment by tarsius** [comment]
`borg-build-mode` which derives from `compilation-mode` is not used because `git` is not a compiler.

We could do all kinds of fancy things with this buffer but because I expect users to see it very seldomly, I would like to avoid geoengineering it.

So just a small improvement to give you the <kbd>q</kbd>:
